<?php
	require_once("inc/config.inc.php");
	$pageheader = "$branding - Pet Central";
 ?>
<html style="--wm-toolbar-height: 68px;">
<?php require_once("inc/head.php"); ?>

<body bgcolor="#FFFFFF" marginwidth="0" marginheight="0" leftmargin="0" topmargin="0" >
 

<?php require("inc/navtop.php"); ?>

<table align="left" border="0" cellpadding="0" cellspacing="0" width="700">
<tbody><tr>

<?php require("inc/sidenav.php");
 if (isset($_SESSION["username"])) { 
 if (!isset($_GET["type"]) or $_GET["type"] != "shop") {
?><td valign="top" width="560"><!--x-->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tbody><tr align="right"> 
<td><img src="/images/headers/explore.gif" width="480" height="62" alt="The Marketplace"></td>
</tr></tbody></table><br clear="all">
<?php require_once("inc/randomevent.php");?>
<table width="100%" border="0" cellspacing="0" cellpadding="5">
	<tbody>
		<tr>
			<td>
				<p><b>The Worlds of <?=$brandingspace?></b></p>
				<p>These are other worlds that have been discovered so far. Why not take your Neopets travelling? Click where you wish to go on the map to explore a whole new part of <?=$brandingspace?>!</p>
			</td>
		</tr>
		<tr align="left"> 
			<td align="center">
				<map name="neopia">
				</map>
				<img src="/images/images/neopia_old_map_4.gif" usemap="#neopia" >
				<p></p>
			</td>
		</tr>
	</tbody>
</table>



 <?php } else {?>
	 <td valign="top" width="560"><!--x-->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tbody><tr align="right"> 
<td><img src="/images/headers/shops/<?=$_GET['obj_type']?>.gif" width="480" height="62" alt="Shop"></td>
</tr></tbody></table><br clear="all">

<table width="100%" border="0" cellspacing="0" cellpadding="5">
	<tbody>
		<tr>
			<td>
				idk how to do this
				<form>
				
				</form>
			</td>
		</tr>
	</tbody>
</table>
	 <?php
	 }
} else {
		require_once("inc/loginform.phtml");
	}?>
</td>
</tr> </tbody></table>
<!-- This is the start of the footer file -->
</td></tr>
</tbody></table><br clear="all">

<?php require("inc/bottom.php"); ?>
<br clear="all"><br>

<!--
     FILE ARCHIVED ON 05:50:00 Feb 01, 2001 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 03:33:41 Feb 23, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
-->
<!--
playback timings (ms):
  captures_list: 0.646
  exclusion.robots: 0.042
  exclusion.robots.policy: 0.032
  esindex: 0.009
  cdx.remote: 29.904
  LoadShardBlock: 300.959 (3)
  PetaboxLoader3.resolve: 210.62 (4)
  PetaboxLoader3.datanode: 151.002 (4)
  load_resource: 165.766
  nav: 0.243 (6)
--></body></html>
	