<?php
	require_once("inc/config.inc.php");
	$pageheader = "$branding - Login Page";
	if (!isset($_SESSION["username"])) {
 ?>
<html style="--wm-toolbar-height: 68px;">
<?php require_once("inc/head.php"); ?>

<body bgcolor="#FFFFFF" marginwidth="0" marginheight="0" leftmargin="0" topmargin="0">
 

<?php require("inc/navtop.php"); ?>

<table align="left" border="0" cellpadding="0" cellspacing="0" width="700">
<tbody><tr>

<?php require("inc/sidenav.php");?>
<td valign="top" width="560">

 
<!-- This is the end of the template file, just before we include the global prefs file -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tbody><tr align="right"> 
    <td><img src="/images/images/header/header_login.gif" width="480" height="62" alt="Login"></td>
  </tr>
</tbody></table><br clear="all"><p>


</p><form action="/login.phtml" method="post">
<table align="center" width="300" cellpadding="4" cellspacing="0">
<input type="hidden" name="destination" value="/petcentral.phtml"><tbody><tr><td bgcolor="#eeeeff">
<b>Username</b>
</td><td bgcolor="#aaaaff">
<input type="text" name="username" value="" size="10" maxlength="20" onfocus="this.select()"></td></tr>

<tr><td bgcolor="#eeeeff">
<b>Password</b>
</td><td bgcolor="#aaaaff">
<input type="password" name="password" value="" size="10" maxlength="20" onfocus="this.select()"></td></tr>

<tr><td bgcolor="#eeeeff">
<b>Remember my User Name/Password?</b>
</td><td bgcolor="#aaaaff" valign="center">
<input type="checkbox" name="userpass"></td></tr>

<tr><td align="center" colspan="2" bgcolor="#ccccff">
<input type="submit" value="Log In to NeoPets!">
</td></tr>

</tbody></table>
</form>


<p>
</p><form action="forgotpassword.phtml">
<center>
Forgotten your password?  Enter your user name in the box below and we will e-mail it to you.
<br>

<input type="text" name="form_username" size="12" maxlength="20">
<input type="submit" value="Go!">


</center></form>


<!-- This is the start of the footer file -->
</td>
</tr> </tbody></table>
<!-- This is the start of the footer file -->
</td></tr>
</tbody></table><br clear="all">

<?php require("inc/bottom.php"); ?>
<br clear="all"><br>

<!--
     FILE ARCHIVED ON 05:50:00 Feb 01, 2001 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 03:33:41 Feb 23, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
-->
<!--
playback timings (ms):
  captures_list: 0.646
  exclusion.robots: 0.042
  exclusion.robots.policy: 0.032
  esindex: 0.009
  cdx.remote: 29.904
  LoadShardBlock: 300.959 (3)
  PetaboxLoader3.resolve: 210.62 (4)
  PetaboxLoader3.datanode: 151.002 (4)
  load_resource: 165.766
  nav: 0.243 (6)
--></body></html>
	<?php } else {
		header("Location: /index.phtml");
	}?>