<?php 
require_once("inc/config.inc.php");

if ($_SERVER['REQUEST_METHOD'] == "POST") {
	$getpet = htmlspecialchars($_POST['petselect']);
	
	$checkpet = $db->prepare("SELECT `owner` FROM `pets` WHERE `name` = ?");
	$checkpet->bind_param("s", $getpet);
	$checkpet->execute();
	$checkpetresult = $checkpet->get_result();
	$checkpetresult2 = mysqli_num_rows($checkpetresult);
	if ($checkpetresult2 == 0) {
		die();
	}
	
	$checkuser = $db->prepare("UPDATE `users` SET `selectedpet`= ? WHERE `username`= ?");
	$checkuser->bind_param("ss", $getpet, $_SESSION["username"]);
	$checkuser->execute();
	header("Refresh:0");
}

	$pageheader = "$branding - Quick Reference";
 ?>
<html style="--wm-toolbar-height: 68px;">
<?php require_once("inc/head.php"); ?>

<body bgcolor="#FFFFFF" marginwidth="0" marginheight="0" leftmargin="0" topmargin="0" >
 

<?php require("inc/navtop.php"); ?>

<table align="left" border="0" cellpadding="0" cellspacing="0" width="700">
<tbody><tr>

<?php require("inc/sidenav.php");
 if (isset($_SESSION["username"])) { 

?><td valign="top" width="560"><!--x-->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tbody><tr align="right"> 
<td><img src="/images/headers/quickref.gif" width="480" height="62" alt="<?=$branding?> - Quick Reference"></td>
</tr></tbody></table><br clear="all">

<table width="100%" border="0" cellspacing="0" cellpadding="5">
	<tbody>
		<tr align="left"> 
			<td>
				<form method="post">
					<div style="display: flex;">
		<?php
			$waaa = $db->prepare("SELECT name, species, color, level, curhealth, maxhealth, mood, strength, defence, movement, intelligence FROM `pets` WHERE `owner` = ?");
			$waaa->bind_param("s", $_SESSION["username"]);
			$waaa->execute();	
			$waaa->bind_result($petnames, $petspecies, $petcolor, $petlevel, $petchealth, $petmhealth, $petmood, $petstrstat, $petdefstat, $petmovstat, $petintstat);
			while ($waaa->fetch()) { 
			
			$petmstat = [
				"1" => "depressed",
				"2" => "very unhappy",
				"3" => "miserable",
				"4" => "unhappy",
				"5" => "content",
				"6" => "happy",
				"7" => "cheerful",
				"8" => "extremely happy",
				"9" => "joyful",
				"10" => "delighted!",
			];
			
			$thirtypercenth = $petmhealth * 0.3;
			$sixtypercenth = $petmhealth * 0.6;
			
			if ($petchealth >= $sixtypercenth) {
				$fonthcolor = "239b56";
			} else if ($petchealth >= $thirtypercenth) {
				$fonthcolor = "bfb513";
			} else {
				$fonthcolor = "e63939";
			}
			
			$petmoodstr = $petmstat[$petmood];
			?>
						<div style="width:fit-content;padding: 10px;">
							<img src="/images/pets/<?=$petspecies?>_<?=$petcolor?>_baby.gif" alt="<?=$petnames?>">
							<center>
								<b><?=$petnames?></b>
								<p>
									<b>Level</b>: <?=$petlevel?> <br>
									<b>Health</b>: <font color="#<?=$fonthcolor?>"><?=$petchealth?>/<?=$petmhealth?></font><br>
									<b>Mood</b>: <?=$petmoodstr?> <br>
								</p>
								<input type="radio" name="petselect" value="<?=$petnames?>"  <?php if ($petname == $petnames) echo 'checked=""' ?>>
							</center>
						
						</div>
		<?php } ?>
					</div>
					<input type="submit">
				</form>
			</td>			
		</tr>
	</tbody>
</table>



<?php } else {
		require_once("inc/loginform.phtml");
	}?>
</td>
</tr> </tbody></table>
<!-- This is the start of the footer file -->
</td></tr>
</tbody></table><br clear="all">

<?php require("inc/bottom.php"); ?>
<br clear="all"><br>

<!--
     FILE ARCHIVED ON 05:50:00 Feb 01, 2001 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 03:33:41 Feb 23, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
-->
<!--
playback timings (ms):
  captures_list: 0.646
  exclusion.robots: 0.042
  exclusion.robots.policy: 0.032
  esindex: 0.009
  cdx.remote: 29.904
  LoadShardBlock: 300.959 (3)
  PetaboxLoader3.resolve: 210.62 (4)
  PetaboxLoader3.datanode: 151.002 (4)
  load_resource: 165.766
  nav: 0.243 (6)
--></body></html>
	



