<?php 

$petslist = [
"1" => "Aisha",
"2" => "Chia",
"3" => "Eyrie",
"4" => "Flotsam",
"5" => "Jetsam",
"6" => "Jubjub",
"7" => "Kacheek",
"8" => "Kiko",
"9" => "Korbat",
"10" => "Lenny",
"11" => "Nimmo",
"12" => "Scorchio",
"13" => "Skeith",
"14" => "Tuskaninny",
"15" => "Uni",
"16" => "Usul",
"17" => "Wocky",
"18" => "Garrl",
"19" => "Buzz",
"20" => "Elephante",
"21" => "Lupe",
"22" => "Gelert",
"23" => "Peophin",
"24" => "Quiggle",
"25" => "Shoyru",
"26" => "Acara",
"27" => "Blumaroo",
"28" => "Zafara",
"29" => "Techo",
"30" => "Mynci",
"31" => "Moehog",
"32" => "Cybunny",
"33" => "Poogle",
"34" => "Kau",
"35" => "Kougra",
"36" => "Grundo",
"37" => "Koi",
"38" => "Bruce",
"39" => "Meerca",
"40" => "Kyrii",
"41" => "Chomby",
"42" => "Pteri",
]
?>